# Generated by Django 2.1.5 on 2019-11-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Profil',
        ),
    ]
