# Generated by Django 2.1.5 on 2019-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0002_auto_20191111_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
