# Generated by Django 2.1.5 on 2019-12-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Массаж'), (2, 'СПА'), (3, 'Медитация')], default=2, verbose_name='Приоритет'),
        ),
    ]
