# Generated by Django 2.1.5 on 2019-12-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('bio', models.BooleanField(blank=True, null=True, verbose_name='Хронические заболевания')),
                ('gip', models.BooleanField(blank=True, null=True, verbose_name='Гипертония')),
                ('gipS', models.CharField(blank=True, max_length=1, null=True, verbose_name='Степень гипертонии')),
                ('var', models.BooleanField(blank=True, null=True, verbose_name='Варикозное расширение вен, нижних конечностей')),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Нет'), (2, 'Воспалительные заболевания'), (3, 'Обострение хронических заболеваний'), (4, 'Месячные')], null=True, verbose_name='Противорпоказания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
